module.exports = {
  CallProperty1: require('./CallProperty1'),
  CallUndefinedReceiver: require('./CallUndefinedReceiver'),
  Debugger: require('./Debugger'),
  Jump: require('./Jump'),
  JumpIfFalse: require('./JumpIfFalse'),
  JumpIfTrue: require('./JumpIfTrue'),
  LdaConstant: require('./LdaConstant'),
  LdaGlobal: require('./LdaGlobal'),
  LdaNamedProperty: require('./LdaNamedProperty'),
  Ldar: require('./Ldar'),
  LdaSmi: require('./LdaSmi'),
  LdaUndefined: require('./LdaUndefined'),
  LdaZero: require('./LdaZero'),
  MulSmi: require('./MulSmi'),
  Return: require('./Return'),
  Star: require('./Star'),
  TestLessThan: require('./TestLessThan'),
};
